theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1:
  - bold
  - italic
  - underline
  - strikethrough
  - separator
  - sub
  - sup
  - charmap
  - separator
  - bullist
  - numlist
  - outdent
  - indent
  - separator
  - blockquote
  - separator
  - link
  - unlink
  - separator
  - cut
  - copy
  - paste
  - undo
  - redo
  - separator
  - fullscreen  
  - separator
  - removeformat
theme_advanced_buttons2:
plugins:
  - fullscreen

